import { AnalysisResult } from '@/components/analysis/AnalysisRunner';

interface ReportMeta {
  adCategory: string;
  adFormat: string;
  platform: string;
  dateChecked: string;
}

export async function generatePDF(result: AnalysisResult, meta: ReportMeta): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const footer = (pageNum: number) => {
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by ASCI Ad Compliance Checker | ${meta.dateChecked} | This report applies ASCI's publicly available code. It is not an official ASCI certification.`,
      margin,
      pageHeight - 10,
      { maxWidth: contentWidth }
    );
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  };

  // ── PAGE 1: SUMMARY ──
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageWidth, 40, 'F');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('ASCI Compliance Report', margin, 25);

  y = 50;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');

  const metaLines = [
    `Category: ${meta.adCategory}`,
    `Format: ${meta.adFormat}`,
    `Platform: ${meta.platform}`,
    `Date Checked: ${meta.dateChecked}`,
  ];
  for (const line of metaLines) {
    doc.text(line, margin, y);
    y += 7;
  }

  y += 8;

  // Score circle (drawn with text)
  doc.setFontSize(48);
  doc.setFont('helvetica', 'bold');
  const scoreColor = result.verdict === 'AUTO_FAIL' || result.overall_score < 60
    ? [220, 38, 38]
    : result.overall_score < 80
    ? [245, 158, 11]
    : [34, 197, 94];
  doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
  doc.text(
    result.verdict === 'AUTO_FAIL' ? 'AUTO-FAIL' : `${result.overall_score}/100`,
    pageWidth / 2,
    y + 20,
    { align: 'center' }
  );

  y += 35;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(result.verdict.replace(/_/g, ' '), pageWidth / 2, y, { align: 'center' });

  y += 12;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  const summaryLines = doc.splitTextToSize(result.full_summary || '', contentWidth);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 6 + 10;

  // Category scores table
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text('Category Score Breakdown', margin, y);
  y += 8;

  const categories = [
    { label: 'Claim Substantiation', key: 'claim_substantiation', max: 25 },
    { label: 'Disclosure Compliance', key: 'disclosure_compliance', max: 25 },
    { label: 'Prohibited Category Check', key: 'prohibited_category_check', max: 20 },
    { label: 'Sector-Specific Rules', key: 'sector_specific', max: 20 },
    { label: 'Language & Framing', key: 'language_and_framing', max: 10 },
  ];

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  for (const cat of categories) {
    const score = result.category_scores[cat.key as keyof typeof result.category_scores];
    const pct = score / cat.max;
    const barWidth = 60;
    const barX = pageWidth - margin - barWidth;

    doc.setTextColor(60, 60, 60);
    doc.text(cat.label, margin, y + 4);
    doc.text(`${score}/${cat.max}`, barX - 12, y + 4, { align: 'right' });

    // Bar background
    doc.setFillColor(230, 230, 230);
    doc.rect(barX, y, barWidth, 5, 'F');

    // Bar fill
    const fillColor = pct >= 0.8 ? [34, 197, 94] : pct >= 0.6 ? [245, 158, 11] : [220, 38, 38];
    doc.setFillColor(fillColor[0], fillColor[1], fillColor[2]);
    doc.rect(barX, y, barWidth * pct, 5, 'F');

    y += 10;
  }

  footer(1);

  // ── VIOLATIONS PAGES ──
  const violations = result.violations;
  let pageNum = 2;

  for (const v of violations) {
    doc.addPage();
    y = margin;

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(30, 41, 59);
    doc.text(`Violation ${v.id}`, margin, y);
    y += 8;

    const sevColor = v.severity === 'HIGH' ? [220, 38, 38] : v.severity === 'MEDIUM' ? [245, 158, 11] : [100, 100, 100];
    doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.roundedRect(margin, y, 22, 7, 2, 2, 'F');
    doc.text(v.severity, margin + 11, y + 5, { align: 'center' });

    doc.setTextColor(100, 100, 100);
    doc.text(v.rule_reference, margin + 26, y + 5);
    doc.text(v.module.replace(/_/g, ' '), pageWidth - margin, y + 5, { align: 'right' });
    y += 14;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text('Offending Element', margin, y);
    y += 6;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    const offendingLines = doc.splitTextToSize(`"${v.offending_element || ''}"`, contentWidth);
    doc.text(offendingLines, margin, y);
    y += offendingLines.length * 5 + 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    doc.text('Why It Violates ASCI Rules', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const whyLines = doc.splitTextToSize(v.why_its_a_violation || '', contentWidth);
    doc.text(whyLines, margin, y);
    y += whyLines.length * 5 + 8;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(22, 163, 74);
    doc.text('Fix Suggestion', margin, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const fixLines = doc.splitTextToSize(v.fix_suggestion || '', contentWidth);
    doc.text(fixLines, margin, y);

    footer(pageNum++);
  }

  // ── COMPLIANT ELEMENTS PAGE ──
  if (result.compliant_elements?.length > 0) {
    doc.addPage();
    y = margin;

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(22, 163, 74);
    doc.text('What Your Ad Got Right', margin, y);
    y += 12;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    for (const el of (result.compliant_elements || [])) {
      const lines = doc.splitTextToSize(`• ${el || ''}`, contentWidth);
      if (y + lines.length * 6 > pageHeight - 20) {
        footer(pageNum++);
        doc.addPage();
        y = margin;
      }
      doc.text(lines, margin, y);
      y += lines.length * 6 + 4;
    }

    footer(pageNum);
  }

  return doc.output('arraybuffer') as ArrayBuffer;
}
